# Generated by Django 4.0.3 on 2022-04-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saballasys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fdesc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='fgpu',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='fmobo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='fname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='fproc',
            field=models.TextField(default=''),
        ),
    ]
