# Generated by Django 4.0.3 on 2022-05-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saballasys', '0002_item_fdesc_item_fgpu_item_fmobo_item_fname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Users',
        ),
    ]
