# Generated by Django 3.1.6 on 2022-07-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saballasys', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_category', models.CharField(choices=[('Processor', 'Processor'), ('Motherboard', 'Motherboard'), ('Graphics Card', 'Graphics Card'), ('RAM', 'RAM'), ('Power Supply', 'Power Supply')], max_length=200, null=True)),
                ('com_name', models.CharField(max_length=200, null=True)),
                ('com_brand', models.CharField(max_length=200, null=True)),
                ('com_specs', models.CharField(max_length=200, null=True)),
                ('com_price', models.IntegerField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
