# Generated by Django 3.1.6 on 2022-07-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saballasys', '0006_auto_20220706_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='com_brand',
        ),
        migrations.RemoveField(
            model_name='components',
            name='com_name',
        ),
        migrations.RemoveField(
            model_name='components',
            name='com_specs',
        ),
        migrations.AddField(
            model_name='components',
            name='gpu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='mobo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='procs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='psu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='ram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='components',
            name='com_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='p_budget',
            field=models.IntegerField(null=True),
        ),
    ]
