# Generated by Django 3.1.6 on 2022-07-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saballasys', '0007_auto_20220706_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='components',
            name='mobo',
        ),
        migrations.RemoveField(
            model_name='components',
            name='procs',
        ),
        migrations.RemoveField(
            model_name='components',
            name='psu',
        ),
        migrations.RemoveField(
            model_name='components',
            name='ram',
        ),
        migrations.AddField(
            model_name='components',
            name='com_brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='com_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='com_specs',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
