# Generated by Django 3.1.6 on 2022-07-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saballasys', '0009_auto_20220706_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='com_brand',
        ),
        migrations.RemoveField(
            model_name='components',
            name='com_category',
        ),
        migrations.RemoveField(
            model_name='components',
            name='com_name',
        ),
        migrations.RemoveField(
            model_name='components',
            name='com_price',
        ),
        migrations.RemoveField(
            model_name='components',
            name='com_specs',
        ),
    ]
