# Generated by Django 3.1.6 on 2022-07-07 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saballasys', '0010_auto_20220706_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='p_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
