# Generated by Django 3.1.6 on 2022-07-07 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saballasys', '0011_info_p_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='p_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
