# Generated by Django 3.1.6 on 2022-07-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saballasys', '0012_auto_20220707_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='p_date',
        ),
    ]
